### ISSUE TITLE
help with different length of time points

### ISSUE THREAD

**Issue by Bmars99** [hkayabilisim/TSCU#2]
Hi Dr.Huseyin Kaya,

Thanks for your kind sharing! 
Here' my problem.
Suppose several time series data are observed, and the length of time points are not the same.
For example, the time series maybe like
[1 2 3 4]
[1 2]
[1 2 3]
I would like to make a classification by applied the DTW mehtod in TSCU. I've checked the tutorial, but I still cannot apply 'tscu' for my problem. Is it possible to use the 'tscu' for the different length of time points?

Appreciate your help !

Best,
Bmars

**Comment by hkayabilisim** [comment]
Hi Bmars,

TSCU does not support this functionality yet. However you can do scaling on x-axis so that they have all the same length. I mean you can stretch the short series by doing interpolation. I know it is destructive process because you are filling in the gaps by creating new data but as far as remember it is one of suggestions in Ramsay's FDA book ( J. O. Ramsay and B. W. Silverman (1997) Functional Data Analysis, New York: Springer.) 

I would like to modify TSCU according to your request but I don't have much time. Until then, I'm afraid you'll have make preprocessing before using TSCU.

Sincerely
Huseyin

**Comment by Bmars99** [comment]
Hi Dr. Kaya,

Thanks for your quick replies and suggestions.
 I'll give it a try and look forward to your more flexible tscu.
Thanks again for your kind sharing!

Sincerely,
Bmars
