### ISSUE TITLE
Data not loading

### ISSUE THREAD

**Issue by wwjd1234** [hkayabilisim/TSCU#5]
When trying to run the load commands I get the following:

Number of columns on line 2 of ASCII file synthetic_control_TRAIN must be the same as previous lines

**Comment by wwjd1234** [comment]
I ended up downloading the files manually, opened in excel, converted to csv and used "csvread" matlab command.

**Comment by hkayabilisim** [comment]
Thank you for pointing out the problem.  It turns out that MATLAB's "urlwrite" is having a problem downloading archive URL. I'm sure that it was working when I published TSCU at GitHub. But, at t some point, I don't know when, wayback machine started producing HTML content that MATLAB's urlwrite can't handle.

Anyhow, I found a very simple workaround by making a very small change in the URL . New URL tells web archive not to create additional HTML content:

Old URL:
https://web.archive.org/web/20150428055342/http://www.cs.ucr.edu/~eamonn/time_series_data

New URL:
https://web.archive.org/web/20150428055342id_/http://www.cs.ucr.edu/~eamonn/time_series_data
