### ISSUE TITLE
Undefined variable 'model'

### ISSUE THREAD

**Issue by wwjd1234** [hkayabilisim/TSCU#6]
When running tscu(trn, tst) everything runs fine but then it also outputs the following:

Undefined function or variable 'model'.

Error in tscu (line 329)
out.svmmodel            = model;

Commenting out that line then re-running the command tscu(trn, tst) gets rid of the error

**Comment by hkayabilisim** [comment]
Thank you the feedback. You are right, even if SVM is not used, it tries to assign out.svmmodel. In my case, it tries to open Simuling model because of name confliction. 

Anyway, I solved it by adding an extra control during assignment and name change.  Can you update your working Git copy by issuing "git pull".
